project:
  type: website
  output-dir: docs

website:
  title: "WZE@Jena"
  search: 
    location: navbar
    type: overlay
  back-to-top-navigation: true
  navbar:
    background: "#175616"
    foreground: "#FFFFFF"
    pinned: true
    left:
      - text: "Standorte"  
        href: standorte.qmd
      - text: "Untersuchungen"  
        href: messungen.qmd
      - text: "Partner"
        href: partner.qmd
  sidebar:
    style: "docked"
    pinned: false
    background: "#248721"
    foreground: "#FFFFFF"
    contents:
    - section: "Standorte"
      href: standorte.qmd
      contents:
      - text: "Untersuchungsflächen"
        href: flaechen.qmd
      - text: "Ökosysteme"  
        href: oekosysteme.qmd
    - section: "Untersuchungen"
      href: messungen.qmd
      contents:
      - text: "Makro- und Mikroklima"
        href: klima.qmd
      - text: "Waldzustand"
        href: waldzustand.qmd
      - text: "Kamerabeobachtungen"
        href: kamerafallen.qmd
      - text: "Boden und Wasserhaushalt"
        href: boden.qmd
      - text: "Bestandsstruktur"
        href: bestandsstruktur.qmd   
  page-footer: 
    left: "Markus Bernhardt-Römermann, Friedrich-Schiller-Universität Jena" 
    background: light
format:
  html:
    theme: materia
    css: styles.css
    toc: true
    toc-title-website: "Inhalt dieser Seite"
    include-in-header:
      - text: |
          <script>window.onload = function() {document.getElementById("autocomplete-0-input").placeholder = "Suche";};</script>

editor: visual

